### ISSUE TITLE
Not working with Better MC Modpack

### ISSUE THREAD

**Issue by kirchner-trevor** [CartoonishVillain/Incapacitated-Fabric#1]
1. Install Better MC modpack https://www.curseforge.com/minecraft/modpacks/better-mc-fabric
2. Add Incapacitated 1.3-1.19.2 fabric to it https://www.curseforge.com/minecraft/mc-mods/incapacitated/files/3981417
3. Join game with a friend and die
4. Go immediately to the death screen

This is without any changes to configuration.

I suspected it may be a conflict with You're In Grave Danger, so I tried removing it, but Incapacitated still doesn't work.

**Comment by CartoonishVillain** [comment]
How exactly are you dying? Some deaths would instantly kill you.

**Comment by CartoonishVillain** [comment]
Specifically speaking, by default (and other mods could add to this list, but that's frankly unlikely) void damage, lava, and wither effects will ignore the incapacitation system

**Comment by kirchner-trevor** [comment]
I tried dying to a polar bear, creeper, and another player. All of those instantly killed me.

**Comment by CartoonishVillain** [comment]
This is almost certainly a mod conflict, or the mod missing on the server, but I'm not sure what exactly the conflict is. By chance, in your logs on startup are there any errors? What about upon your death?

Also, are you certain that the server you're joining, or the host of the LAN connection you may be joining has the mod installed as well?

**Comment by kirchner-trevor** [comment]
I didn't see any errors on startup or death, it's a server I am running so I'm sure I've just screwed something up. 

I will try a fresh install and confirm later today. Just wanted to see if you had run into anything like this before.

I didn't see any dependencies listed on the CurseForge page but are there any specific libraries I need Installed on the server other than Incapacitated?

**Comment by CartoonishVillain** [comment]
Only cloth config api. 

I'd imagine it's a server issue (maybe outdated version? Maybe dependency missing? Maybe just accidentally not installed?) easiest way to double check is to see if the issue persists in singleplayer.

**Comment by kirchner-trevor** [comment]
Confirmed incapacitated is working correctly, I think I may have installed the forge version or was missing cloth config api.
